package com.miguelcr.a04_fruits.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.miguelcr.a04_fruits.db.Fruits;

import com.miguelcr.a04_fruits.db.FruitsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fruitsDaoConfig;

    private final FruitsDao fruitsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fruitsDaoConfig = daoConfigMap.get(FruitsDao.class).clone();
        fruitsDaoConfig.initIdentityScope(type);

        fruitsDao = new FruitsDao(fruitsDaoConfig, this);

        registerDao(Fruits.class, fruitsDao);
    }
    
    public void clear() {
        fruitsDaoConfig.clearIdentityScope();
    }

    public FruitsDao getFruitsDao() {
        return fruitsDao;
    }

}
