package com.miguelcr.a04_fruits.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "FRUITS".
 */
@Entity
public class Fruits {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Integer icon;
    private Integer quantity;

    @Generated
    public Fruits() {
    }

    public Fruits(Long id) {
        this.id = id;
    }

    @Generated
    public Fruits(Long id, String name, Integer icon, Integer quantity) {
        this.id = id;
        this.name = name;
        this.icon = icon;
        this.quantity = quantity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIcon() {
        return icon;
    }

    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

}
